### ISSUE TITLE
Improve Vue <script setup lang="ts"> handling

### ISSUE THREAD

**Issue by yusufkandemir** [unjs/mkdist#209]
### Describe the feature

Currently, `<script setup lang="ts">` is being completely bypassed, as of #15. However, bypassing should only be needed when using type-only macros, e.g. `defineProps<{ foo: number }>()`(_not `defineProps({ foo: Number })`_).

So, to improve this:
- Quick and acceptable solution: do not exclude files that don't have any type-only macros
- Best solution: avoid bypassing completely by converting type-only macros to their runtime definition counterparts, e.g. convert `defineProps<{ foo: number }>()` to `defineProps({ foo: number })`. This may be complex to implement, and may even require help from the Vue team. The reverse of https://github.com/sapphi-red/vue-convert-to-script-setup-from-composition-api may work.

I will implement the "quick and acceptable solution" soon.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Teages** [comment]
I have some idea and I made the another vue mkdist loader around it.

Take a look: https://github.com/Teages/mkdist-vue-loader

It looks great but I don't know should I merge it back to mkdist because it would break the original code structure (although just a little, it will transfer `<script setup>` to `<script>`) and a bit slow (in my test case, it takes 15% longer)
